### ISSUE TITLE
Center position

### ISSUE THREAD

**Issue by grafa** [alertifyjs/alertify.js#104]
Hey there,

first of all I'd like to say well done.

Do you think it's possible to add center position for top and bottom? Some oldschool clients demand to have the message on top but centered. I guess position "top center" would do the job.

Thanks in advance.

**Comment by bogal** [comment]
I too would like to see the notification positioned in the centre, but to the left or right of the screen (ie. like bottom left, but half-way up the display).

**Comment by winni4eva** [comment]
Also trying to position the alerts on the top right of the screen. Whats the best way to go about this.

**Comment by heymackey** [comment]
@grafa I also wanted to have `top center` position. Here's what I added with my own css class to get centered horizontally. Since `.top` and `.bottom` are independent positioning, you don't need to worry about them, adding this "just works™" on [almost all current browsers](http://caniuse.com/#search=transform)

``` css
.alertify-logs.center {
  left: 0;
  width: 100%;
}
.alertify-logs.center > .default,
.alertify-logs.center > .success,
.alertify-logs.center > .error {
  left: 50%;
  transform: translateX(-50%);
  text-align: center;
}
```

and then

``` js
alertify.logPosition("top center");
alertify.success("I'm all centered!");
```

@bogal I'd assume you could try the same with a custom css class like `.middle` and do some vertical aligning. It would get paired with `.left` and `.right` that come with the default css.

``` css
.alertify-logs.middle {
  height: 100%;
}
.alertify-logs.middle > .default,
.alertify-logs.middle > .success,
.alertify-logs.middle > .error {
  top: 50%;
  transform: translateY(-50%);
}
```

and then 

``` js
alertify.logPosition("middle right");
alertify.success("Stuck in the middle with you");
```

@winni4eva, for alerts, I believe that's supposed to always be centered vertically and horizontally (mimicking browser alert boxes). if you mean for the logs (success, error, etc), you can do (as [described here](https://alertifyjs.org/#log-messages)):

```
alertify.logPosition("top right");
alertify.log("Hello from the upper right");
```
