### ISSUE TITLE
Is it possible to align at top center?

### ISSUE THREAD

**Issue by masimao** [alertifyjs/alertify.js#24]
Hi,

Is it possible to align the notifications at top center of the page?

Thanks!

**Comment by bradberger** [comment]
Sorry for the delay in responding. Yes, it is. This seems to be working for me:

```css
.alertify-logs {
    width: 50% !important;
    top: 0px !important;
    left: 25% !important;
    right: 25% !important;
    bottom: initial !important;
}
```

You'll just have to add it to any of your CSS files after including the Alertify css file.
